SCREEN_WIDTH = 1366
SCREEN_HEIGHT = 768

PLAYER_SIZE_X = 32
PLAYER_SIZE_Y = 32

MAP_SIZE_X = 200
MAP_SIZE_Y = 160
MUTIPIE_SIZE = SCREEN_HEIGHT/MAP_SIZE_Y
MAP_START_POSITION_X = (SCREEN_WIDTH-(MAP_SIZE_X * MUTIPIE_SIZE))/2 
MAP_START_POSITION_Y = (SCREEN_HEIGHT-(MAP_SIZE_Y * MUTIPIE_SIZE))/2


SHOWHITBOX = False

TILESIZE = 32
FPS = 60


# ============================================== Layer ===========================================
HITBOX_LAYER = 7
TEXT_LAYER = 6
BLOOD_BAG = 6
BLOOD_STORAGE = 6
OBJECT_LAYER = 6
PLAYER_LAYER = 5
SPAWN_NPC = 5
NPC_LAYER = 4
BED_DOWN_LAYER = 4
NPC_LAYER_ON_BED = 3
NPC_LAYER_ON_BED = 3
BED_LAYER = 2
MAP_LAYER = 1


PLAYER_SPEED = 6

# ============================================== Color ===========================================

RED_BLOOD =(255, 91, 91 )
RED_BLOOD_SHADOW = (128, 0, 17)
WHITE = (255, 255, 255)
WHITE_FONT = (243, 244, 255)
GRAY_FONT = (188, 197, 209)
GRAY_SHADOW_FONT = (57, 62, 87)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)

# WALLSCAL = 